# Wire up travis
language: python
sudo: false

addons:
  firefox: "43.0"

services:
  - xvfb

matrix:
  include:
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
      dist: xenial
      sudo: true
    - python: 3.8-dev
      env: TOXENV=py38
      dist: xenial
      sudo: true
    - python: "pypy"
      env: TOXENV=pypy
    - python: "pypy3"
      env: TOXENV=pypy3
    - python: "3.6"
      env: TOXENV=py36-cover,coverage
    - python: "3.6"
      env: TOXENV=docs
    - python: "3.6"
      env: TOXENV=lint
    - python: "3.6"
      env: TOXENV=functional3
  allow_failures:
      - env: TOXENV=py38

install:
  - travis_retry pip install tox

# For Selenium
# https://docs.travis-ci.com/user/gui-and-headless-browsers/
# http://stackoverflow.com/a/34703838/315168
# https://benlimmer.com/2019/01/14/travis-ci-xvfb/
before_script:
  - "export DISPLAY=:99.0"
  - echo "Extracting firefox and setting PATH variable..."
  - tar -xjf /tmp/firefox-43.0.tar.bz2 --directory /tmp
  - export PATH="/tmp/firefox:$PATH"
  - echo "Using firefox version `firefox --version`"

script:
  - travis_retry tox

notifications:
  email:
    - pyramid-checkins@lists.repoze.org
  irc:
    channels:
      - "chat.freenode.net#pyramid"
